### ISSUE TITLE
Configurable Kroki endpoint

### ISSUE THREAD

**Issue by blaggacao** [JoelCourtney/mdbook-kroki-preprocessor#1]
Using this for eventually sensitive data is not possible when the public endpoint is hard-coded.

Can you make the endpoint configurable?

**Comment by JoelCourtney** [comment]
Sure I can do that. Would you like me to publish this to crates.io? I never ended up using this crate, so I didn't fully document or publish it. It shouldn't be much trouble though, so I can do that tomorrow if you think you'll use it.

**Comment by blaggacao** [comment]
Great! I definitely plan to use it as part of github.com/divnix/std for the md-book instrumentation w.r.t. architecture documentation. So this would be great. I'd be consuming a build from `nixpkgs` via #3 , that'd be perfectly enough, so no need for publishing to crates.io on my end. Thx!!

**Comment by JoelCourtney** [comment]
Do you have a kroki instance you can test against? I've added the endpoint configuration, but I don't have a custom instance set up to test it.

edit: nevermind got it working.
