### ISSUE TITLE
Table renderer is broken 

### ISSUE THREAD

**Issue by GTrunSec** [JoelCourtney/mdbook-kroki-preprocessor#5]
- Unable to render table when kroki-preprocessor enabled.

- Test Contents. related [issue](https://github.com/divnix/std/pull/79)

```

|  Target                       | std |rustc|cargo| notes                      |
|-------------------------------|-----|-----|-----|----------------------------|
| `x86_64-unknown-linux-musl`   |  ✓  |     |     | 64-bit Linux with MUSL     |
| `arm-linux-androideabi`       |  ✓  |     |     | ARM Android                |
| `arm-unknown-linux-gnueabi`   |  ✓  |  ✓  |     | ARM Linux (2.6.18+)        |
| `arm-unknown-linux-gnueabihf` |  ✓  |  ✓  |     | ARM Linux (2.6.18+)        |
| `aarch64-unknown-linux-gnu`   |  ✓  |     |     | ARM64 Linux (2.6.18+)      |
| `mips-unknown-linux-gnu`      |  ✓  |     |     | MIPS Linux (2.6.18+)       |
| `mipsel-unknown-linux-gnu`    |  ✓  |     |     | MIPS (LE) Linux (2.6.18+)  |
```

**Comment by JoelCourtney** [comment]
Interesting, not sure why this is happening. I probably won't be able to investigate and get a fix until around Tuesday. Thanks for reporting!

**Comment by JoelCourtney** [comment]
This was actually a problem with pulldown_cmark and pulldown_cmark_to_cmark not recognizing some formatting styles for tables. I've enabled all extra options in pulldown_cmark and it now recognizes all tables. Version 0.1.1 is now available on crates.io. Thanks!

**Comment by GTrunSec** [comment]
Good job, thanks.
