### ISSUE TITLE
Reading the kroki from a file

### ISSUE THREAD

**Issue by GTrunSec** [JoelCourtney/mdbook-kroki-preprocessor#7]
This is a feature request that enables us to read graph data through the `including file`
  - https://rust-lang.github.io/mdBook/format/mdbook.html#including-portions-of-a-file

- example: 

```
 ```kroki-PlantUML                                                                                                  
   {{#include ./md.plum}}                                                                                             
```

**Comment by blaggacao** [comment]
Isn't this covered via https://github.com/JoelCourtney/mdbook-kroki-preprocessor/blob/main/example/src/subchapters/subchapter.md?

**Comment by GTrunSec** [comment]
@blaggacao thanks for pointing this key out, my bad. Oops
